[book]
    authors      = ["Luca Palmieri"]
    language     = "en"
    multilingual = false
    src          = "src"
    title        = "100 Exercises To Learn Rust"

[preprocessor.exercise-linker]
    exercise_root_url = "https://github.com/mainmatter/100-exercises-to-learn-rust/tree/main/exercises"

[preprocessor.link-shortener]
    after     = ["exercise-linker"]
    base_url  = "https://ruex.io"
    mapping   = "link2alias.json"
    renderers = ["pandoc"]
    verify    = false

[output.html]
    git-repository-url = "https://github.com/mainmatter/100-exercises-to-learn-rust"

[output.pandoc]
    hosted-html = "https://rust-exercises.com/100-exercises/"
    optional    = true

    [output.pandoc.code]
        show-hidden-lines = true

    [output.pandoc.profile.pdf] # options to pass to Pandoc (see https://pandoc.org/MANUAL.html)
        highlight-style = "./custom.theme"
        output-file     = "100-exercises-to-learn-rust.pdf"
        to              = "latex"
        # We use `lualatext` because, right now, it's the only engine
        # that supports fallback fonts, which we need for emojis.
        metadata-file = "metadata.yml"
        pdf-engine    = "lualatex"

        [output.pandoc.profile.pdf.variables]
            mainfont = "CoreSansA45.ttf"
            mainfontoptions = [
                "BoldFont=CoreSansA65.ttf",
                "BoldItalicFont=CoreSansA65It.ttf",
                "ItalicFont=CoreSansA45It.ttf",
            ]
            sansfont = "CoreSansA45.ttf"
            sansfontoptions = [
                "BoldFont=CoreSansA65.ttf",
                "BoldItalicFont=CoreSansA65It.ttf",
                "ItalicFont=CoreSansA45It.ttf",
            ]
            # You can get these fonts here: https://fonts.google.com/selection?query=noto+color+
            documentclass = "book"
            fontsize = "10pt"
            geometry = "papersize={8in,10in},top=2cm,bottom=2cm,left=2.4cm,right=2.4cm"
            header-includes = [
                "\\definecolor{Links}{HTML}{6200EE}",
                # Reduce font size of code blocks
                "\\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\\\\{\\},fontsize=\\small}",
            ]
            linkcolor = "Links"
            mainfontfallback = ["Open Sans:style=Regular"]
            monofont = "Noto Sans Mono"
            monofontfallback = ["Noto Color Emoji:mode=harf"]
            sansfontfallback = ["Open Sans:style=Regular"]
            urlcolor = "Links"
            urlstyle = "rm"

    [output.pandoc.profile.paperback]
        highlight-style = "monochrome"
        metadata-file   = "metadata.yml"
        output-file     = "100-exercises-to-learn-rust.pdf"
        to              = "latex"
        # We use `lualatext` because, right now, it's the only engine
        # that supports fallback fonts, which we need for emojis.
        pdf-engine = "lualatex"

        [output.pandoc.profile.paperback.variables]
            mainfont = "CoreSansA45.ttf"
            mainfontoptions = [
                "BoldFont=CoreSansA65.ttf",
                "BoldItalicFont=CoreSansA65It.ttf",
                "ItalicFont=CoreSansA45It.ttf",
            ]
            sansfont = "CoreSansA45.ttf"
            sansfontoptions = [
                "BoldFont=CoreSansA65.ttf",
                "BoldItalicFont=CoreSansA65It.ttf",
                "ItalicFont=CoreSansA45It.ttf",
            ]
            # You can get these fonts here: https://fonts.google.com/selection?query=noto+color+
            documentclass = "book"
            fontsize = "10pt"
            geometry = "papersize={8in,10in},top=2cm,bottom=2cm,left=2.8cm,right=2.5cm"
            header-includes = [
                "\\definecolor{Links}{HTML}{6200EE}",
                # Reduce font size of code blocks
                "\\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\\\\{\\},fontsize=\\small}",
            ]
            linkcolor = "Links"
            links-as-notes = true
            mainfontfallback = ["Open Sans:style=Regular"]
            monofont = "Noto Sans Mono"
            monofontfallback = ["Noto Color Emoji:mode=harf"]
            sansfontfallback = ["Open Sans:style=Regular"]
            urlcolor = "Links"
            urlstyle = "rm"

    # We go through HTML, rather than directly to ePUB, since routing
    # Pandoc's HTML through Calibre's ePUB converter gives us better results.
    [output.pandoc.profile.html]
        embed-resources = true
        highlight-style = "monochrome"
        metadata-file   = "metadata.yml"
        output-file     = "100-exercises-to-learn-rust.html"
        standalone      = true
        to              = "html"

        [output.pandoc.profile.html.variables]
            # You can get these fonts here: https://fonts.google.com/selection?query=noto+color+
            mainfontfallback = ["Open Sans:style=Regular"]
            monofont         = "Noto Sans Mono"
            monofontfallback = ["Noto Color Emoji:mode=harf"]
            sansfontfallback = ["Open Sans:style=Regular"]
            urlstyle         = "rm"
